In [6]:
import queries

In [5]:
df = queries.get_upcoming_matches_with_predictions()
df

AttributeError: module 'queries' has no attribute 'get_upcoming_matches_with_predictions'

In [7]:
a = '2020-02-26 06:00:00.0000000'
':'.join(a.split(':')[:-1])

'2020-02-26 06:00'

In [ ]:
list(df.T.to_dict().values())

In [ ]:
sql = '''select tor.Name as tournament, bets.HomeTeamName, bets.HomeTeamId, bets.AwayTeamName, bets.AwayTeamId, bets.StartTime, bets.LeagueId, bets.isLive, odds.Value as home_odds, odds2.Value as away_odds
            from (select * from dbo.bets where bets.StartTime > GETDATE() and bets.LeagueId='00000000-0000-0000-0000-000000000cd6') as bets 
            INNER JOIN dbo.tournaments as tor 
            ON (bets.tournament = tor.Id)
            INNER JOIN (select * from dbo.markets where Name = 'Match Winner') as mk 
            ON (bets.Id = mk.MatchId)
            INNER JOIN dbo.odds as odds
            on (odds.MarketId = mk.Id and odds.Name = bets.HomeTeamName)
            INNER JOIN dbo.odds as odds2
            on (odds2.MarketId = mk.Id and odds2.Name = bets.AwayTeamName)
            order by bets.StartTime asc;'''
    
df = run_custom_query(sql)

In [11]:
df = queries.get_upcoming_matches_with_predictions()

In [14]:
df.head()

,tournament,HomeTeamName,HomeTeamId,AwayTeamName,AwayTeamId,StartTime,LeagueId,isLive,home_odds,away_odds
0,2020 [CSGO] LOOT.BET/CS Season 6,Gambit Youngsters,2eb1d17c-c9df-4891-66cf-1e45a6cca5f5,Heretics,a2807997-5add-3b6c-9c75-790efb7a2098,2020-04-09 09:55:00.0000000,00000000-0000-0000-0000-000000000cd6,False,1.75,2.01
1,2020 [CSGO] Home Sweet Home Cup (Season 1),Movistar Riders,747ea90a-2e64-8824-350d-7544e3eefd8e,Japaleno,65c09ece-0e93-16f8-a221-843c488e8c0e,2020-04-09 10:00:00.0000000,00000000-0000-0000-0000-000000000cd6,False,1.65,2.15
2,2020 [CSGO] Home Sweet Home Cup (Season 1),North,c218663e-b2f2-dde0-7bfb-e49dbd493048,Sprout,91076b00-e115-f707-9071-8d04df5cf9fe,2020-04-09 11:30:00.0000000,00000000-0000-0000-0000-000000000cd6,False,1.5,2.48
3,2020 [CSGO] eFire Master League Season 1 North...,SHIFT,1d8dbcd0-aabb-64ef-59fb-9763f5a574b8,ExsequoR,2a30b443-e028-03dc-0337-7bca5eb49b40,2020-04-09 12:00:00.0000000,00000000-0000-0000-0000-000000000cd6,False,2.42,1.52
4,2020 [CSGO] LOOT.BET/CS Season 6,SKADE,beb22374-7e8e-9121-3594-2b90331d409b,Endpoint,38d7fd3a-7849-921e-1e5e-2fdd427eb54e,2020-04-09 12:55:00.0000000,00000000-0000-0000-0000-000000000cd6,False,1.72,2.05

In [ ]:
#http://108.31.152.188:8000/home/get_prediction?team1=DETONA&team2=RED%20Canidis&datetime=2020-03-09%2018:30:00

In [35]:
df.iloc[0].StartTime.rsplit('.')[0]

'2020-04-09 09:55:00'

In [23]:
a = '2020-03-09 18:30:00'

In [39]:
def get_prediction_from_series(series):
    pred = get_prediction(series.HomeTeamName, series.AwayTeamName, series.StartTime.rsplit('.')[0],
                                min_odds=0.2,
                                lookback=12,
                                lags=1,
                                rolling_w=3,
                                min_games=None,
                                verbose=False,
                                debug=False,
                                divide=False,
                                hypothesis_test=False)
    bet_on = "Don't Bet"
    if pred[0][0]:
        bet_on = series.HomeTeamName
    elif pred[0][1]:
        bet_on = series.AwayTeamName
    return(bet_on)

df['bet_on'] = df.apply(get_prediction_from_series, axis=1)

In [40]:
results

0     Don't Bet
1     Don't Bet
2     Don't Bet
3     Don't Bet
4     Don't Bet
5     Don't Bet
6     Don't Bet
7     Don't Bet
8     Don't Bet
9     MAD Lions
10    Don't Bet
11    Don't Bet
12    Don't Bet
13    Don't Bet
14    Don't Bet
15        Ignis
16    Don't Bet
17    Don't Bet
18    Don't Bet
19    Don't Bet
20    Don't Bet
dtype: object

In [41]:
get_prediction('MAD Lions', 'Ignis', a,
                                min_odds=0.2,
                                lookback=12,
                                lags=1,
                                rolling_w=3,
                                min_games=None,
                                verbose=False,
                                debug=False,
                                divide=False,
                                hypothesis_test=False)

[[0, 0, 1]]

In [5]:
def calculate_net_change(series):
    if series.skip_bet:
        return(0)
    elif not series.correct:
        return(-1 * series.amount)
    else:
        if series.HomeTeamName == series.bet_on:
            return((series.home_odds-1)*series.amount)
        else:
            return((series.away_odds-1)*series.amount)

In [6]:
df['net_change'] = df.apply(calculate_net_change, axis=1).cumsum()

In [16]:
import predict

ModuleNotFoundError: No module named 'csgobetting'

In [4]:
df

NameError: name 'df' is not defined

In [ ]:
predict.get_prediction(team1,team2,datetime)

In [30]:
get_prediction(team_a, team_b, date_time,
                                min_odds=1e-4,
                                lookback=3,
                                lags=1,
                                rolling_w=2,
                                min_games=None,
                                verbose=True,
                                debug=False,
                                divide=True,
                                hypothesis_test=False)

NameError: name 'team_a' is not defined

In [ ]:
import queries
import odds_loss_function

In [28]:
def monthdelta(date, delta):
    m, y = (date.month+delta) % 12, date.year + ((date.month)+delta-1) // 12
    if not m: m = 12
    d = min(date.day, [31,
        29 if y%4==0 and not y%400==0 else 28,31,30,31,30,31,31,30,31,30,31][m-1])
    return date.replace(day=d,month=m, year=y)

def get_timeseries_for_team(df, team, time=datetime.now(), lookback=1):
    #Create X=[map]([1-hot team 1] + [1-hot team 2]), y=[alphabetically order ratio] style of data
    df = df.loc[np.array(df.index < time) & np.array(df.index > monthdelta(time, -lookback))]
    matches = df.groupby(['match_id',
                          'team_name',
                          'match_datetime']).mean().reset_index(level=1).join(df.groupby(['match_id',
                                                                                          'team_name',
                                                                                          'match_datetime']).mean().reset_index(level=1), lsuffix='_a', rsuffix='_b')
    matches = matches.loc[matches['team_name_a'] != matches['team_name_b']]
    matches.columns = [x.replace('_assists','') for x in matches.columns]
    
    matches = matches.loc[np.array(matches['team_name_a'] == team) + np.array(matches['team_name_b'] == team)]
    
    def sort_team_names(series, team):
        pair = [series['team_name_a'],series['team_name_b']]
        pair.sort()
        #Need to reorder the stats if swapping teams
        if series['team_name_b'] == team:
            #print(pair)
            copy_series = series.copy()
            for col in series.index:
                if '_a' in col:
                    base = col.split('_a')[0]
                    series[col] = copy_series[base+'_b']
                elif '_b' in col:
                    base = col.split('_b')[0]
                    series[col] = copy_series[base+'_a']
        return(series)
    
    matches = matches.apply(sort_team_names, args=[team], axis=1)
    matches = matches.drop_duplicates()
    
    matches = matches.groupby(['match_datetime','team_name_a','team_name_b']).mean()
    matches = matches.reset_index(level=1).reset_index(level=1) 

    matches['win_ratio'] = matches['rounds_won_a']/(matches['rounds_won_b']+matches['rounds_won_a'])

    team_matches = matches.drop(['kills_b', 'headshots_b', 'assists_b', 'flash_b', 
                                      'deaths_b', 'kast_b', 'kd_diff_b', 'adr_b', 'first_kill_diff_b', 
                                      'rating_b', 'pistol_wins_b', 'rounds_won_b', 'rounds_lost_b'], axis=1)
    team_matches.columns = [x.replace('_a','') for x in team_matches.columns]
    
    return(team_matches)

def create_var_results(team_matches, lags=1):
    data = team_matches.to_numpy()
    model = VAR(data)
    model_fit = model.fit(lags, trend='nc')
    yhat = model_fit.forecast_interval(data, 1)
    return(pd.DataFrame([x[0] for x in yhat], index=[['mean', 'lower','upper']], columns=team_matches.columns)['win_ratio'])

def get_prob_success(ci, alpha=0.05, hypothesis_test=True):
    if np.nan in ci:
        return(0)
    if not hypothesis_test:
        return(ci[0])
    sigma = (ci[2]-ci[0])/norm_signif_level(alpha)
    z = (1-ci[0])/sigma
    return(1-st.norm.cdf(z))

def clean_timeseries(team_matches, min_games=1, rolling_w=1, categorical=False):
    #if categorical:
    #    team_matches = team_matches
    team_matches = team_matches[team_matches.columns[team_matches.dtypes == float]]
    team_matches = team_matches.dropna(axis=1)
    if rolling_w > 1:
        team_matches = team_matches.rolling(rolling_w).mean()
        team_matches = team_matches.dropna()
    assert(team_matches.shape[0] > min_games), "Not enough rows: " + str(team_matches.shape[0])
    #team_matches = CATEGORICAL 
    team_matches.loc[:, (team_matches != df.iloc[0]).any()]
    assert ('win_ratio' in team_matches.columns),"'win_ratio' not in columns"
    return(team_matches)

def norm_signif_level(alpha=0.05):
    return st.norm.ppf(1 - alpha)

def get_prediction(team_a, team_b, date_time,
                                min_odds=1e-4,
                                lookback=3,
                                lags=1,
                                rolling_w=2,
                                min_games=None,
                                verbose=True,
                                debug=False,
                                divide=True,
                                hypothesis_test=True):
    
    ts = pd.to_datetime(date_time)
    
    df = queries.get_historic_match_data_from_date(date_time,lookback)
    df['match_datetime'] = pd.to_datetime(df['match_datetime'])
    df = df.set_index('match_datetime')
    df = df.sort_index()
    df = df.drop_duplicates()
    
    if not min_games:
        min_games = max(lags,rolling_w) + 1

    chance_of_victory = 0
    chance_win = np.nan
    chance_loss = np.nan

    try:
        team_matches = get_timeseries_for_team(df, team_a, time=ts, lookback=lookback).sort_index()
        team_matches = clean_timeseries(team_matches, min_games, rolling_w=rolling_w)
        chance_win  = get_prob_success(create_var_results(team_matches, lags=lags), hypothesis_test=hypothesis_test)

        team_matches = get_timeseries_for_team(df, team_b, time=ts, lookback=lookback).sort_index()
        team_matches = clean_timeseries(team_matches, min_games, rolling_w=rolling_w)
        chance_loss = get_prob_success(create_var_results(team_matches, lags=lags), hypothesis_test=hypothesis_test)


    except AssertionError as e:
        if debug: 
            print(str(e) + "\n" + str(ts) + " '" + team_a + "' vs '" + team_b + "' doesn't have enough matches")

    if divide:
        chance_of_victory = (chance_win / chance_loss)
        should_bet = (np.abs(chance_of_victory) < min_odds and chance_of_victory < 1) or (1/np.abs(chance_of_victory) < min_odds and chance_of_victory > 1)
        bet_on = 0 if chance_of_victory > 1 else 1
    else:
        chance_of_victory = (chance_win - chance_loss)
        should_bet = np.abs(chance_of_victory) > min_odds
        bet_on = 0 if chance_of_victory > 0 else 1

    if np.isnan(chance_of_victory):
        should_bet = False

    prediction = [[0,0,0]]
    if not should_bet:
        prediction[0][2] = 1
    else:
        prediction[0][bet_on] = 1
            
    return(prediction)

In [7]:
df

,StartTime,HomeTeamName,AwayTeamName,amount,bet_on,confidence,skip_bet,correct,home_odds,away_odds,net_change
0,2020-01-19,Faze,NiP,4.0,NiP,0.1,0,0,1.5,3.5,-4.0
1,2020-01-30,Faze,NiP,6.0,NiP,0.1,0,1,1.8,1.7,0.2
2,2020-01-31,Faze,NiP,5.0,NiP,0.5,1,1,1.2,5.1,0.2

In [9]:
list(df['net_change'].values)

[-4.0, 0.1999999999999993, 0.1999999999999993]

In [10]:
temp = df.copy()

In [11]:
temp

,StartTime,HomeTeamName,AwayTeamName,amount,bet_on,confidence,skip_bet,correct,home_odds,away_odds,net_change
0,2020-01-19,Faze,NiP,4.0,NiP,0.1,0,0,1.5,3.5,-4.0
1,2020-01-30,Faze,NiP,6.0,NiP,0.1,0,1,1.8,1.7,0.2
2,2020-01-31,Faze,NiP,5.0,NiP,0.5,1,1,1.2,5.1,0.2

In [12]:
temp = temp.set_index('StartTime')

In [13]:
temp

,HomeTeamName,AwayTeamName,amount,bet_on,confidence,skip_bet,correct,home_odds,away_odds,net_change
StartTime,,,,,,,,,,
2020-01-19,Faze,NiP,4.0,NiP,0.1,0,0,1.5,3.5,-4.0
2020-01-30,Faze,NiP,6.0,NiP,0.1,0,1,1.8,1.7,0.2
2020-01-31,Faze,NiP,5.0,NiP,0.5,1,1,1.2,5.1,0.2

In [15]:
temp['net_change'].to_dict()

{Timestamp('2020-01-19 00:00:00'): -4.0,
 Timestamp('2020-01-30 00:00:00'): 0.1999999999999993,
 Timestamp('2020-01-31 00:00:00'): 0.1999999999999993}

In [22]:
import numpy as np

In [25]:
df['StartTime'].astype(np.int64) / int(1e6)

0    1.579392e+12
1    1.580342e+12
2    1.580429e+12
Name: StartTime, dtype: float64

In [33]:
','.join(['{' + str(df['StartTime'].iloc[i]) + ',' + str(df['net_change'].iloc[i]) + "}" for i in range(df.shape[0])])

'{2020-01-19 00:00:00,-4.0},{2020-01-30 00:00:00,0.1999999999999993},{2020-01-31 00:00:00,0.1999999999999993}'

In [28]:
df.shape[0]

3

In [29]:
str(df['StartTime'].iloc(1))

ValueError: No axis named 1 for object type <class 'pandas.core.series.Series'>